'use client';
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';

type Lead={id:number;name:string;phone:string;email?:string;company?:string;status:string;system_size:number;battery_kwh:number;investment:number;saving:number;payback:number;created_at:string};
type Project={id:number;lead_id:number;project_code:string;name:string;status:string;project_value:number;system_size:number;contact_name:string;phone:string;quotation_number?:string;quotation_amount?:number;quotation_status?:string};
type Pipeline={status:string;count:number;value:number};
type QuoteSummary={open_count:number;open_value:number;accepted_value:number};
const leadLabels:Record<string,string>={NEW:'ใหม่',CONTACTED:'ติดต่อแล้ว',SURVEY:'นัดสำรวจ',PROPOSAL:'เสนอราคา',WON:'ปิดการขาย',LOST:'ไม่สำเร็จ'};
const projectLabels:Record<string,string>={SURVEY:'สำรวจ',DESIGN:'ออกแบบ',QUOTATION:'เสนอราคา',NEGOTIATION:'เจรจา',WON:'ชนะ',LOST:'แพ้'};
const money=(value:number|string|undefined)=>`฿${Math.round(Number(value||0)).toLocaleString('th-TH')}`;

export default function Admin(){
 const [leads,setLeads]=useState<Lead[]>([]),[projects,setProjects]=useState<Project[]>([]),[pipeline,setPipeline]=useState<Pipeline[]>([]),[quoteSummary,setQuoteSummary]=useState<QuoteSummary>({open_count:0,open_value:0,accepted_value:0}),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=async()=>{setLoading(true);try{const [leadRes,projectRes]=await Promise.all([fetch('/api/leads',{cache:'no-store'}),fetch('/api/projects',{cache:'no-store'})]);if(leadRes.status===401||projectRes.status===401){location.href='/admin/login';return}const [leadData,projectData]=await Promise.all([leadRes.json(),projectRes.json()]);if(!leadData.ok)throw new Error(leadData.error);if(!projectData.ok)throw new Error(projectData.error);setLeads(leadData.leads);setProjects(projectData.projects);setPipeline(projectData.pipeline);setQuoteSummary(projectData.quotationSummary||{});setError('')}catch(e){setError(e instanceof Error?e.message:'โหลดข้อมูลไม่สำเร็จ')}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>leads.filter(x=>`${x.name} ${x.phone} ${x.email||''} ${x.company||''}`.toLowerCase().includes(q.toLowerCase())),[leads,q]);
 const projectByLead=useMemo(()=>new Map(projects.map(p=>[Number(p.lead_id),p])),[projects]);
 const pipelineMap=useMemo(()=>new Map(pipeline.map(p=>[p.status,p])),[pipeline]);
 const leadStatus=async(id:number,status:string)=>{await fetch(`/api/leads/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status})});load()};
 const convert=async(id:number)=>{const r=await fetch(`/api/leads/${id}/convert`,{method:'POST'});const d=await r.json();if(d.ok)location.href=`/admin/projects/${d.project.id}`;else setError(d.error||'แปลง Lead ไม่สำเร็จ')};
 const del=async(id:number)=>{if(!confirm('ยืนยันลบ Lead และ Project ที่เกี่ยวข้อง?'))return;await fetch(`/api/leads/${id}`,{method:'DELETE'});load()};
 const pipelineValue=pipeline.reduce((sum,item)=>item.status==='WON'||item.status==='LOST'?sum:sum+Number(item.value||0),0);
 return <main className="adminPage"><header className="adminTop"><div><b>VES.</b><span>Solar CRM</span></div><div className="adminNav"><a href="/">Calculator</a><form action="/api/admin/logout" method="post"><button>ออกจากระบบ</button></form></div></header>
 <section className="adminHero"><p>PHASE 3.3 · SALES OPERATIONS</p><h1>Sales & Project Dashboard</h1><div className="adminStats"><article><span>Projects ทั้งหมด</span><b>{projects.length}</b></article><article><span>มูลค่า Pipeline</span><b>{money(pipelineValue)}</b></article><article><span>ใบเสนอราคาเปิด</span><b>{quoteSummary.open_count||0}</b><small>{money(quoteSummary.open_value)}</small></article><article><span>ยอดขายที่ชนะ</span><b>{money(quoteSummary.accepted_value)}</b></article></div></section>
 <section className="adminContent"><div className="sectionHead"><div><p className="eyebrow">PIPELINE SUMMARY</p><h2>ภาพรวมขั้นตอนการขาย</h2></div><button className="refreshBtn" onClick={load}>Refresh</button></div><div className="pipelineGrid">{Object.entries(projectLabels).map(([status,label])=>{const item=pipelineMap.get(status);return <article key={status} className={`pipelineCard status-${status.toLowerCase()}`}><span>{label}</span><b>{item?.count||0} โครงการ</b><small>{money(item?.value)}</small></article>})}</div>
 {error&&<div className="adminError">{error}<small>ตรวจสอบ DATABASE_URL และ Environment Variables ของ deployment</small></div>}{loading?<p>กำลังโหลด...</p>:<><div className="sectionHead projectTitle"><div><p className="eyebrow">ACTIVE PROJECTS</p><h2>Projects และใบเสนอราคา</h2></div></div><div className="leadTableWrap"><table className="leadTable projectTable"><thead><tr><th>Project</th><th>ลูกค้า</th><th>ระบบ</th><th>มูลค่า</th><th>Pipeline</th><th>ใบเสนอราคาล่าสุด</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td><Link className="projectLink" href={`/admin/projects/${p.id}`}><b>{p.project_code}</b><span>{p.name}</span></Link></td><td><b>{p.contact_name}</b><span>{p.phone}</span></td><td><b>{Number(p.system_size||0).toFixed(1)} kWp</b></td><td><b>{money(p.project_value)}</b></td><td><span className={`statusBadge status-${p.status.toLowerCase()}`}>{projectLabels[p.status]||p.status}</span></td><td>{p.quotation_number?<><b>{p.quotation_number}</b><span>{money(p.quotation_amount)} · {p.quotation_status}</span></>:<span>ยังไม่มี</span>}</td></tr>)}</tbody></table>{!projects.length&&<p className="empty">ยังไม่มี Project — แปลง Lead ด้านล่างเพื่อเริ่มต้น</p>}</div>
 <div className="sectionHead leadTitle"><div><p className="eyebrow">LEAD INBOX</p><h2>Lead ทั้งหมด</h2></div><input placeholder="ค้นหาชื่อ เบอร์โทร บริษัท Email..." value={q} onChange={e=>setQ(e.target.value)}/></div><div className="leadTableWrap"><table className="leadTable"><thead><tr><th>ลูกค้า</th><th>ระบบ</th><th>การเงิน</th><th>สถานะ</th><th>วันที่</th><th>Project</th><th></th></tr></thead><tbody>{rows.map(x=>{const project=projectByLead.get(Number(x.id));return <tr key={x.id}><td><b>{x.name}</b><span>{x.phone}</span><small>{x.company||x.email||'-'}</small></td><td><b>{Number(x.system_size||0).toFixed(1)} kWp</b><span>{Number(x.battery_kwh||0)} kWh Battery</span></td><td><b>{money(x.investment)}</b><span>Save {money(x.saving)}/ปี</span><small>Payback {Number(x.payback||0).toFixed(1)} ปี</small></td><td><select value={x.status} onChange={e=>leadStatus(x.id,e.target.value)}>{Object.entries(leadLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></td><td>{new Date(x.created_at).toLocaleDateString('th-TH')}</td><td>{project?<Link className="smallBtn" href={`/admin/projects/${project.id}`}>{project.project_code}</Link>:<button className="convertBtn" onClick={()=>convert(x.id)}>แปลงเป็น Project</button>}</td><td><button className="deleteBtn" onClick={()=>del(x.id)}>ลบ</button></td></tr>})}</tbody></table>{!rows.length&&<p className="empty">ยังไม่มี Lead</p>}</div></>}</section></main>
}
