'use client';
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useState} from 'react';
const LocationMap=dynamic(()=>import('@/components/LocationMap'),{ssr:false});
const months=['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'];
const fallback=[132,145,166,164,151,130,125,128,126,125,119,120];
function irr(c:number[]){let low=-.99,high=2;for(let n=0;n<100;n++){const x=(low+high)/2;let npv=-c[0];for(let i=1;i<c.length;i++)npv+=c[i]/Math.pow(1+x,i);if(npv>0)low=x;else high=x}return (low+high)/2*100}
export default function Home(){
 const [bill,setBill]=useState(5000),[dayUse,setDayUse]=useState(60),[tariff,setTariff]=useState(4.2),[type,setType]=useState('บ้านพักอาศัย'),[lat,setLat]=useState(14.3532),[lng,setLng]=useState(100.5689),[investmentPerKw,setInvestmentPerKw]=useState(28000),[discount,setDiscount]=useState(6),[degradation,setDegradation]=useState(.5),[solar,setSolar]=useState(fallback),[loading,setLoading]=useState(false),[source,setSource]=useState('ค่าประมาณเริ่มต้น');
 const loadSolar=async(a=lat,o=lng)=>{setLoading(true);try{const d=await fetch(`/api/solar?lat=${a}&lng=${o}`).then(x=>x.json());if(d.monthlyIrradiance){setSolar(d.monthlyIrradiance);setSource(`Open-Meteo · เฉลี่ย ${d.period.start} ถึง ${d.period.end}`)}}finally{setLoading(false)}};
 useEffect(()=>{loadSolar()},[]);
 const gps=()=>navigator.geolocation?.getCurrentPosition(p=>{const a=p.coords.latitude,o=p.coords.longitude;setLat(a);setLng(o);loadSolar(a,o)},()=>alert('ไม่สามารถอ่าน GPS ได้ กรุณาอนุญาต Location'));
 const r=useMemo(()=>{const monthlyLoad=bill/tariff,usable=monthlyLoad*dayUse/100,size=Math.ceil(Math.max(1,usable/120)*2)/2,pr=.80,production=solar.map(x=>x*size*pr),annual=production.reduce((a,b)=>a+b,0),used=Math.min(annual,monthlyLoad*12*dayUse/100),saving=used*tariff,investment=size*investmentPerKw,payback=investment/Math.max(saving,1),roi=saving/investment*100,cash=[investment],flows=[] as number[];let cum=-investment;for(let y=1;y<=25;y++){const f=saving*Math.pow(1-degradation/100,y-1);flows.push(f);cash.push(f);cum+=f}const npv=-investment+flows.reduce((s,f,i)=>s+f/Math.pow(1+discount/100,i+1),0);return{size,production,annual,saving,investment,payback,roi,npv,irr:irr(cash),flows,co2:annual*.499}},[bill,dayUse,tariff,solar,investmentPerKw,discount,degradation]);
 const pdf=async()=>{const el=document.getElementById('report');if(!el)return;const [{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')]);const canvas=await html2canvas(el,{scale:1.6,useCORS:true,backgroundColor:'#ffffff'});const img=canvas.toDataURL('image/jpeg',.9),doc=new jsPDF('p','mm','a4'),w=190,h=canvas.height*190/canvas.width;let y=10,left=h;doc.addImage(img,'JPEG',10,y,w,h);left-=277;while(left>0){y-=277;doc.addPage();doc.addImage(img,'JPEG',10,y,w,h);left-=277}doc.save(`VES-Solar-Report-${r.size.toFixed(1)}kWp.pdf`)};
 return <main><nav><div className="brand"><span className="ves">VES</span><span className="dot"/><b>Solar Calculate</b></div><a href="#calculator">Phase 2.1</a></nav>
 <section className="hero"><div><p className="eyebrow">VES SOLAR ENERGY · PHASE 2.1</p><h1>Solar GIS +<br/><span>Financial Analysis</span></h1><p>เลือกตำแหน่งจากแผนที่หรือ GPS วิเคราะห์รังสีอาทิตย์ตามพิกัด ผลผลิต 12 เดือน และกระแสเงินสด 25 ปี</p><a className="primary" href="#calculator">เริ่มวิเคราะห์ →</a></div><div className="sun"><div className="panel">☀<strong>{r.size.toFixed(1)} kWp</strong><small>{Math.round(r.annual).toLocaleString()} kWh/ปี</small></div></div></section>
 <section id="calculator" className="locationSec"><div className="locationHead"><div><p className="eyebrow">SITE LOCATION</p><h2>เลือกตำแหน่งติดตั้ง</h2><p>คลิกบนแผนที่ หรือใช้ GPS ของอุปกรณ์</p></div><button onClick={gps}>◎ ใช้ตำแหน่ง GPS</button></div><LocationMap lat={lat} lng={lng} onPick={(a,o)=>{setLat(a);setLng(o);loadSolar(a,o)}}/><div className="coords"><span>Latitude <b>{lat.toFixed(6)}</b></span><span>Longitude <b>{lng.toFixed(6)}</b></span><button onClick={()=>loadSolar()}>{loading?'กำลังโหลด...':'อัปเดต Solar Data'}</button></div><small className="dataSource">Solar data: {source}</small></section>
 <div id="report"><section className="calculator"><div className="form"><p className="eyebrow">PROJECT INPUT</p><h2>สมมติฐานโครงการ</h2><label>ประเภทผู้ใช้<select value={type} onChange={e=>setType(e.target.value)}><option>บ้านพักอาศัย</option><option>ธุรกิจ / SME</option><option>โรงงานอุตสาหกรรม</option></select></label><label>ค่าไฟเฉลี่ย/เดือน (บาท)<input type="number" value={bill} onChange={e=>setBill(+e.target.value)}/></label><div className="two"><label>ค่าไฟ (บาท/kWh)<input type="number" step=".01" value={tariff} onChange={e=>setTariff(+e.target.value)}/></label><label>ลงทุนต่อ kWp<input type="number" value={investmentPerKw} onChange={e=>setInvestmentPerKw(+e.target.value)}/></label></div><label>ใช้ไฟช่วงกลางวัน <b>{dayUse}%</b><input type="range" min="10" max="100" value={dayUse} onChange={e=>setDayUse(+e.target.value)}/></label><div className="two"><label>Discount Rate (%)<input type="number" step=".1" value={discount} onChange={e=>setDiscount(+e.target.value)}/></label><label>Degradation (%/ปี)<input type="number" step=".1" value={degradation} onChange={e=>setDegradation(+e.target.value)}/></label></div><p className="hint">ใช้ Performance Ratio 80% และ GHI จากพิกัดเพื่อประมาณ AC energy เบื้องต้น ควรสำรวจหน้างาน/เงาบัง/ทิศและมุมหลังคาก่อนออกแบบจริง</p></div>
 <div className="results"><p>VES ANALYSIS RESULT</p><strong className="big">{r.size.toFixed(1)} <small>kWp</small></strong><div className="grid"><article><span>☀️ ผลิตไฟ/ปี</span><b>{Math.round(r.annual).toLocaleString()} kWh</b></article><article><span>💰 ประหยัด/ปี</span><b>฿{Math.round(r.saving).toLocaleString()}</b></article><article><span>📈 ROI ปีแรก</span><b>{r.roi.toFixed(1)}%</b></article><article><span>⏱️ Payback</span><b>{r.payback.toFixed(1)} ปี</b></article><article><span>NPV 25 ปี</span><b>฿{Math.round(r.npv).toLocaleString()}</b></article><article><span>IRR</span><b>{r.irr.toFixed(1)}%</b></article></div><button onClick={pdf}>ดาวน์โหลด VES PDF Report</button></div></section>
 <section className="chartSec"><p className="eyebrow">SOLAR IRRADIANCE & PRODUCTION</p><h2>Production 12 เดือนตามพิกัด</h2><div className="bars">{r.production.map((v,i)=><div className="barWrap" key={months[i]}><span>{Math.round(v)}</span><div className="bar" style={{height:`${Math.max(25,v/Math.max(...r.production)*180)}px`}}/><small>{months[i]}</small></div>)}</div><p className="chartNote">หน่วยกราฟ: kWh/เดือน · Annual GHI ≈ {Math.round(solar.reduce((a,b)=>a+b,0)).toLocaleString()} kWh/m²/ปี</p></section>
 <section className="cashSec"><p className="eyebrow">25 YEAR CASH FLOW</p><h2>กระแสเงินสดสะสม 25 ปี</h2><div className="cashGrid">{r.flows.map((v,i)=><article key={i}><span>ปี {i+1}</span><b>฿{Math.round(v).toLocaleString()}</b></article>)}</div></section></div>
 <section className="features"><h2>VES Solar Financial Snapshot</h2><div><article>01<h3>Solar GIS</h3><p>พิกัด {lat.toFixed(4)}, {lng.toFixed(4)} พร้อมข้อมูล GHI ตามตำแหน่ง</p></article><article>02<h3>Investment</h3><p>ลงทุนประมาณ ฿{Math.round(r.investment).toLocaleString()} · Payback {r.payback.toFixed(1)} ปี</p></article><article>03<h3>25-Year Value</h3><p>NPV ฿{Math.round(r.npv).toLocaleString()} · IRR {r.irr.toFixed(1)}%</p></article></div></section><footer><b>VES Solar Calculate · Phase 2.1</b><span>V Engineering Solutions Co., Ltd. · www.vengineering.co.th</span></footer></main>;
}