'use client';
import dynamic from 'next/dynamic';
import {useEffect,useMemo,useState} from 'react';
const LocationMap=dynamic(()=>import('@/components/LocationMap'),{ssr:false});
const months=['ม.ค.','ก.พ.','มี.ค.','เม.ย.','พ.ค.','มิ.ย.','ก.ค.','ส.ค.','ก.ย.','ต.ค.','พ.ย.','ธ.ค.'];
const fallback=[132,145,166,164,151,130,125,128,126,125,119,120];
const packages=[{id:'value',name:'VES VALUE',panel:'Jinko Class Module',inverter:'On-grid Inverter',battery:'ไม่รวม Battery',factor:.96},{id:'smart',name:'VES SMART',panel:'Jinko Class Module',inverter:'Huawei Class Inverter',battery:'Battery Ready',factor:1},{id:'hybrid',name:'VES HYBRID',panel:'Premium PV Module',inverter:'Sigenergy Class Hybrid',battery:'Sigen Battery Ready',factor:1.18}];
function calcIrr(inv:number,flows:number[]){let low=-.99,high=2;for(let n=0;n<100;n++){const x=(low+high)/2;let npv=-inv;flows.forEach((f,i)=>npv+=f/Math.pow(1+x,i+1));if(npv>0)low=x;else high=x}return (low+high)/2*100}
export default function Home(){
 const [bills,setBills]=useState(Array(12).fill(5000)),[dayUse,setDayUse]=useState(60),[tariff,setTariff]=useState(4.2),[type,setType]=useState('บ้านพักอาศัย'),[lat,setLat]=useState(14.3532),[lng,setLng]=useState(100.5689),[investmentPerKw,setInvestmentPerKw]=useState(28000),[discount,setDiscount]=useState(6),[degradation,setDegradation]=useState(.5),[solar,setSolar]=useState(fallback),[loading,setLoading]=useState(false),[source,setSource]=useState('ค่าประมาณเริ่มต้น'),[tariffMode,setTariffMode]=useState('Flat'),[onPeak,setOnPeak]=useState(5.8),[offPeak,setOffPeak]=useState(2.8),[onPeakShare,setOnPeakShare]=useState(65),[demandKw,setDemandKw]=useState(0),[demandRate,setDemandRate]=useState(0),[demandReduction,setDemandReduction]=useState(0),[batteryKwh,setBatteryKwh]=useState(0),[batteryCost,setBatteryCost]=useState(12000),[batteryEfficiency,setBatteryEfficiency]=useState(90),[packageId,setPackageId]=useState('smart'),[lead,setLead]=useState({name:'',phone:'',email:'',company:'',note:''}),[leadStatus,setLeadStatus]=useState('');
 const pkg=packages.find(x=>x.id===packageId)!;
 const loadSolar=async(a=lat,o=lng)=>{setLoading(true);try{const d=await fetch(`/api/solar?lat=${a}&lng=${o}`).then(x=>x.json());if(d.monthlyIrradiance){setSolar(d.monthlyIrradiance);setSource(`Open-Meteo · เฉลี่ย ${d.period.start} ถึง ${d.period.end}`)}}finally{setLoading(false)}};
 useEffect(()=>{loadSolar()},[]);
 const gps=()=>navigator.geolocation?.getCurrentPosition(p=>{const a=p.coords.latitude,o=p.coords.longitude;setLat(a);setLng(o);loadSolar(a,o)},()=>alert('ไม่สามารถอ่าน GPS ได้ กรุณาอนุญาต Location'));
 const r=useMemo(()=>{const annualBill=bills.reduce((a,b)=>a+b,0),avgBill=annualBill/12,avgRate=tariffMode==='TOU'?onPeak*onPeakShare/100+offPeak*(1-onPeakShare/100):tariff,monthlyLoad=avgBill/Math.max(avgRate,.01),usable=monthlyLoad*dayUse/100,size=Math.ceil(Math.max(1,usable/120)*2)/2,pr=.80,production=solar.map(x=>x*size*pr),annual=production.reduce((a,b)=>a+b,0),dayEnergy=monthlyLoad*12*dayUse/100,solarUsed=Math.min(annual,dayEnergy),batteryShift=Math.min(Math.max(annual-solarUsed,0),batteryKwh*365)*batteryEfficiency/100,energySaving=(solarUsed+batteryShift)*avgRate,demandSaving=Math.min(demandKw,demandReduction)*demandRate*12,saving=energySaving+demandSaving,solarInvestment=size*investmentPerKw*pkg.factor,batteryInvestment=batteryKwh*batteryCost,investment=solarInvestment+batteryInvestment,payback=investment/Math.max(saving,1),roi=saving/Math.max(investment,1)*100,flows=[] as number[];for(let y=1;y<=25;y++)flows.push(saving*Math.pow(1-degradation/100,y-1));const npv=-investment+flows.reduce((s,f,i)=>s+f/Math.pow(1+discount/100,i+1),0);return{annualBill,avgBill,avgRate,size,production,annual,solarUsed,batteryShift,energySaving,demandSaving,saving,solarInvestment,batteryInvestment,investment,payback,roi,npv,irr:calcIrr(investment,flows),flows,co2:annual*.499}},[bills,dayUse,tariff,tariffMode,onPeak,offPeak,onPeakShare,solar,investmentPerKw,discount,degradation,demandKw,demandRate,demandReduction,batteryKwh,batteryCost,batteryEfficiency,pkg]);
 const setBill=(i:number,v:number)=>setBills(x=>x.map((b,j)=>j===i?v:b));
 const pdf=async()=>{const el=document.getElementById('report');if(!el)return;const [{default:html2canvas},{jsPDF}]=await Promise.all([import('html2canvas'),import('jspdf')]);const canvas=await html2canvas(el,{scale:1.5,useCORS:true,backgroundColor:'#fff'});const img=canvas.toDataURL('image/jpeg',.9),doc=new jsPDF('p','mm','a4'),w=190,h=canvas.height*190/canvas.width;let y=10,left=h;doc.addImage(img,'JPEG',10,y,w,h);left-=277;while(left>0){y-=277;doc.addPage();doc.addImage(img,'JPEG',10,y,w,h);left-=277}doc.save(`VES-Solar-Report-${r.size.toFixed(1)}kWp.pdf`)};
 const submitLead=async(e:React.FormEvent)=>{e.preventDefault();setLeadStatus('กำลังส่งข้อมูล...');const res=await fetch('/api/leads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...lead,package:pkg.name,systemSize:r.size,batteryKwh,investment:r.investment,saving:r.saving,payback:r.payback,lat,lng})});const d=await res.json();setLeadStatus(d.ok?'รับข้อมูลแล้ว ทีม VES สามารถนำผลวิเคราะห์นี้ไปจัดทำข้อเสนอได้':'ส่งข้อมูลไม่สำเร็จ: '+(d.error||'กรุณาลองใหม่'))};
 return <main><nav><div className="brand"><span className="ves">VES</span><span className="dot"/><b>Solar Calculate</b></div><a href="#calculator">Phase 3</a></nav>
 <section className="hero"><div><p className="eyebrow">VES SOLAR ENERGY · PHASE 3</p><h1>Solar Analysis<br/><span>to Sales Proposal</span></h1><p>จาก Solar GIS และ Financial Analysis สู่การเลือก Package, สรุปงบประมาณ และส่งข้อมูลเพื่อจัดทำข้อเสนอ VES</p><a className="primary" href="#calculator">เริ่มวิเคราะห์ →</a></div><div className="sun"><div className="panel">☀<strong>{r.size.toFixed(1)} kWp</strong><small>{pkg.name}</small></div></div></section>
 <section id="calculator" className="locationSec"><div className="locationHead"><div><p className="eyebrow">SITE LOCATION</p><h2>ตำแหน่งติดตั้ง + Solar GIS</h2></div><button onClick={gps}>◎ ใช้ตำแหน่ง GPS</button></div><LocationMap lat={lat} lng={lng} onPick={(a,o)=>{setLat(a);setLng(o);loadSolar(a,o)}}/><div className="coords"><span>Latitude <b>{lat.toFixed(6)}</b></span><span>Longitude <b>{lng.toFixed(6)}</b></span><button onClick={()=>loadSolar()}>{loading?'กำลังโหลด...':'อัปเดต Solar Data'}</button></div><small className="dataSource">Solar data: {source}</small></section>
 <div id="report"><section className="billSec"><p className="eyebrow">12 MONTH ELECTRICITY BILL</p><h2>ค่าไฟย้อนหลัง 12 เดือน</h2><div className="billGrid">{bills.map((b,i)=><label key={i}><span>{months[i]}</span><input type="number" value={b} onChange={e=>setBill(i,+e.target.value)}/></label>)}</div><div className="billSummary"><span>รวมค่าไฟ/ปี <b>฿{Math.round(r.annualBill).toLocaleString()}</b></span><span>เฉลี่ย/เดือน <b>฿{Math.round(r.avgBill).toLocaleString()}</b></span></div></section>
 <section className="packageSec"><p className="eyebrow">VES SOLAR PACKAGE</p><h2>เลือกแนวทางอุปกรณ์สำหรับประมาณราคา</h2><div className="packageGrid">{packages.map(p=><button key={p.id} className={packageId===p.id?'packageCard active':'packageCard'} onClick={()=>setPackageId(p.id)}><strong>{p.name}</strong><span>{p.panel}</span><span>{p.inverter}</span><span>{p.battery}</span><b>{p.factor===1?'มาตรฐาน':p.factor<1?'Value Cost':'Premium'}</b></button>)}</div><p className="hint">Package ใช้สำหรับประมาณการเบื้องต้น ไม่ใช่ใบเสนอราคาสุดท้าย รุ่นอุปกรณ์ จำนวนแผง และราคาจริงต้องยืนยันจากการออกแบบ/สำรวจหน้างาน</p></section>
 <section className="calculator"><div className="form"><p className="eyebrow">ENERGY & TARIFF</p><h2>รูปแบบการใช้ไฟ</h2><label>ประเภทผู้ใช้<select value={type} onChange={e=>setType(e.target.value)}><option>บ้านพักอาศัย</option><option>ธุรกิจ / SME</option><option>โรงงานอุตสาหกรรม</option></select></label><label>รูปแบบอัตราค่าไฟ<select value={tariffMode} onChange={e=>setTariffMode(e.target.value)}><option value="Flat">Flat Rate</option><option value="TOU">TOU (กำหนดเอง)</option></select></label>{tariffMode==='Flat'?<label>ค่าไฟเฉลี่ย (บาท/kWh)<input type="number" step=".01" value={tariff} onChange={e=>setTariff(+e.target.value)}/></label>:<><div className="two"><label>On Peak (บาท/kWh)<input type="number" step=".01" value={onPeak} onChange={e=>setOnPeak(+e.target.value)}/></label><label>Off Peak (บาท/kWh)<input type="number" step=".01" value={offPeak} onChange={e=>setOffPeak(+e.target.value)}/></label></div><label>สัดส่วน On Peak <b>{onPeakShare}%</b><input type="range" min="0" max="100" value={onPeakShare} onChange={e=>setOnPeakShare(+e.target.value)}/></label></>}<label>ใช้ไฟช่วงกลางวัน <b>{dayUse}%</b><input type="range" min="10" max="100" value={dayUse} onChange={e=>setDayUse(+e.target.value)}/></label><div className="two"><label>ลงทุน Solar / kWp<input type="number" value={investmentPerKw} onChange={e=>setInvestmentPerKw(+e.target.value)}/></label><label>Discount Rate (%)<input type="number" step=".1" value={discount} onChange={e=>setDiscount(+e.target.value)}/></label></div><label>Degradation (%/ปี)<input type="number" step=".1" value={degradation} onChange={e=>setDegradation(+e.target.value)}/></label></div>
 <div className="form"><p className="eyebrow">INDUSTRIAL + BATTERY</p><h2>Demand & Battery Simulation</h2><div className="two"><label>Maximum Demand (kW)<input type="number" value={demandKw} onChange={e=>setDemandKw(+e.target.value)}/></label><label>Demand Charge (บาท/kW)<input type="number" value={demandRate} onChange={e=>setDemandRate(+e.target.value)}/></label></div><label>คาดว่าลด Demand ได้ (kW)<input type="number" value={demandReduction} onChange={e=>setDemandReduction(+e.target.value)}/></label><div className="two"><label>Battery Capacity (kWh)<input type="number" value={batteryKwh} onChange={e=>setBatteryKwh(+e.target.value)}/></label><label>Battery Cost (บาท/kWh)<input type="number" value={batteryCost} onChange={e=>setBatteryCost(+e.target.value)}/></label></div><label>Round-trip Efficiency <b>{batteryEfficiency}%</b><input type="range" min="60" max="100" value={batteryEfficiency} onChange={e=>setBatteryEfficiency(+e.target.value)}/></label><div className="miniResults"><span>Battery Investment <b>฿{Math.round(r.batteryInvestment).toLocaleString()}</b></span><span>Demand Saving <b>฿{Math.round(r.demandSaving).toLocaleString()}/ปี</b></span><span>Battery Shift <b>{Math.round(r.batteryShift).toLocaleString()} kWh/ปี</b></span></div></div></section>
 <section className="results resultWide"><p>VES PHASE 3 ANALYSIS · {pkg.name}</p><strong className="big">{r.size.toFixed(1)} <small>kWp Solar {batteryKwh>0?`+ ${batteryKwh} kWh Battery`:''}</small></strong><div className="grid metricGrid"><article><span>ผลิตไฟ/ปี</span><b>{Math.round(r.annual).toLocaleString()} kWh</b></article><article><span>ประหยัดรวม/ปี</span><b>฿{Math.round(r.saving).toLocaleString()}</b></article><article><span>เงินลงทุนประมาณ</span><b>฿{Math.round(r.investment).toLocaleString()}</b></article><article><span>Payback</span><b>{r.payback.toFixed(1)} ปี</b></article><article><span>ROI ปีแรก</span><b>{r.roi.toFixed(1)}%</b></article><article><span>NPV 25 ปี</span><b>฿{Math.round(r.npv).toLocaleString()}</b></article><article><span>IRR</span><b>{r.irr.toFixed(1)}%</b></article><article><span>CO₂ ลดลง</span><b>{(r.co2/1000).toFixed(1)} ton/ปี</b></article></div><button onClick={pdf}>ดาวน์โหลด VES PDF Report</button></section>
 <section className="chartSec"><p className="eyebrow">12 MONTH PRODUCTION</p><h2>Solar Production ตามพิกัด</h2><div className="bars">{r.production.map((v,i)=><div className="barWrap" key={months[i]}><span>{Math.round(v)}</span><div className="bar" style={{height:`${Math.max(25,v/Math.max(...r.production)*180)}px`}}/><small>{months[i]}</small></div>)}</div></section>
 <section className="cashSec"><p className="eyebrow">25 YEAR CASH FLOW</p><h2>กระแสเงินสด 25 ปี</h2><div className="cashGrid">{r.flows.map((v,i)=><article key={i}><span>ปี {i+1}</span><b>฿{Math.round(v).toLocaleString()}</b></article>)}</div></section></div>
 <section className="leadSec"><div><p className="eyebrow">VES LEAD & PROPOSAL</p><h2>ขอให้ VES จัดทำข้อเสนอจากผลวิเคราะห์นี้</h2><p>ระบบจะส่งข้อมูลโครงการ ขนาด Solar, Package, งบประมาณ และผลตอบแทนไปยังขั้นตอน Lead/CRM</p></div><form onSubmit={submitLead}><div className="two"><label>ชื่อ-นามสกุล *<input required value={lead.name} onChange={e=>setLead({...lead,name:e.target.value})}/></label><label>เบอร์โทรศัพท์ *<input required value={lead.phone} onChange={e=>setLead({...lead,phone:e.target.value})}/></label></div><div className="two"><label>Email<input type="email" value={lead.email} onChange={e=>setLead({...lead,email:e.target.value})}/></label><label>บริษัท / หน่วยงาน<input value={lead.company} onChange={e=>setLead({...lead,company:e.target.value})}/></label></div><label>รายละเอียดเพิ่มเติม<textarea value={lead.note} onChange={e=>setLead({...lead,note:e.target.value})}/></label><div className="proposalSummary"><b>{pkg.name}</b><span>{r.size.toFixed(1)} kWp</span><span>ประมาณ ฿{Math.round(r.investment).toLocaleString()}</span><span>Payback {r.payback.toFixed(1)} ปี</span></div><button type="submit">ส่งข้อมูลเพื่อจัดทำข้อเสนอ</button>{leadStatus&&<p className="leadStatus">{leadStatus}</p>}</form></section>
 <section className="features"><h2>Phase 3 Sales Workflow</h2><div><article>01<h3>Analyze</h3><p>Solar GIS + ค่าไฟ + TOU + Demand + Battery</p></article><article>02<h3>Select Package</h3><p>เลือกแนวทางอุปกรณ์และระดับงบประมาณก่อนออกแบบจริง</p></article><article>03<h3>Lead → Proposal</h3><p>ส่งผลวิเคราะห์เข้าสู่ขั้นตอน CRM และจัดทำข้อเสนอ</p></article></div></section><footer><b>VES Solar Calculate · Phase 3</b><span>V Engineering Solutions Co., Ltd. · www.vengineering.co.th</span></footer></main>;
}