'use client';
import Link from 'next/link';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {useParams} from 'next/navigation';

type Project={id:number;project_code:string;name:string;status:string;project_value:number;system_size:number;battery_kwh:number;owner?:string;site_address?:string;note?:string;contact_name:string;phone:string;email?:string;company?:string;lead_note?:string;estimated_investment:number;saving:number;payback:number;lat?:number;lng?:number};
type Quotation={id:number;quotation_number:string;version:number;amount:number;status:string;valid_until?:string;note?:string;created_at:string};
const statuses:Record<string,string>={SURVEY:'สำรวจหน้างาน',DESIGN:'ออกแบบระบบ',QUOTATION:'จัดทำใบเสนอราคา',NEGOTIATION:'เจรจาต่อรอง',WON:'ชนะการขาย',LOST:'ไม่สำเร็จ'};
const quoteStatuses:Record<string,string>={DRAFT:'ฉบับร่าง',SENT:'ส่งแล้ว',ACCEPTED:'ลูกค้ายอมรับ',REJECTED:'ถูกปฏิเสธ',EXPIRED:'หมดอายุ'};
const money=(value:number|string|undefined)=>`฿${Math.round(Number(value||0)).toLocaleString('th-TH')}`;

export default function ProjectDetail(){
 const {id}=useParams<{id:string}>();const [project,setProject]=useState<Project|null>(null),[quotes,setQuotes]=useState<Quotation[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saving,setSaving]=useState(false),[quote,setQuote]=useState({amount:'',validUntil:'',note:''});
 const load=useCallback(async()=>{setLoading(true);try{const r=await fetch(`/api/projects/${id}`,{cache:'no-store'});if(r.status===401){location.href='/admin/login';return}const d=await r.json();if(!d.ok)throw new Error(d.error);setProject(d.project);setQuotes(d.quotations);setQuote(q=>({...q,amount:q.amount||String(d.project.project_value||d.project.estimated_investment||'')}));setError('')}catch(e){setError(e instanceof Error?e.message:'โหลด Project ไม่สำเร็จ')}finally{setLoading(false)}},[id]);
 useEffect(()=>{load()},[load]);
 const update=(key:keyof Project,value:string|number)=>setProject(p=>p?{...p,[key]:value}:p);
 const save=async(e:FormEvent)=>{e.preventDefault();if(!project)return;setSaving(true);const r=await fetch(`/api/projects/${id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({name:project.name,status:project.status,projectValue:project.project_value,owner:project.owner,siteAddress:project.site_address,note:project.note})});const d=await r.json();if(d.ok){setProject(p=>p?{...p,...d.project}:p);setError('')}else setError(d.error);setSaving(false)};
 const createQuote=async(e:FormEvent)=>{e.preventDefault();const r=await fetch(`/api/projects/${id}/quotations`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({amount:quote.amount,validUntil:quote.validUntil,note:quote.note})});const d=await r.json();if(d.ok){setQuote({amount:'',validUntil:'',note:''});load()}else setError(d.error)};
 const quoteStatus=async(quotationId:number,status:string)=>{const r=await fetch(`/api/quotations/${quotationId}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({status})});const d=await r.json();if(d.ok)load();else setError(d.error)};
 if(loading)return <main className="adminPage"><p className="pageState">กำลังโหลด Project...</p></main>;
 if(!project)return <main className="adminPage"><p className="pageState">{error||'ไม่พบ Project'} · <Link href="/admin">กลับ Dashboard</Link></p></main>;
 return <main className="adminPage"><header className="adminTop"><div><b>VES.</b><span>Solar CRM</span></div><div className="adminNav"><Link href="/admin">← Dashboard</Link><form action="/api/admin/logout" method="post"><button>ออกจากระบบ</button></form></div></header>
 <section className="detailHero"><div><p>PROJECT DETAIL</p><h1>{project.project_code}</h1><span>{project.name}</span></div><div><span>มูลค่าโครงการ</span><b>{money(project.project_value)}</b></div></section>
 <section className="detailGrid"><div className="detailMain">{error&&<div className="adminError">{error}</div>}<form className="detailCard projectForm" onSubmit={save}><div className="cardHead"><div><p className="eyebrow">PROJECT PROFILE</p><h2>ข้อมูลและสถานะโครงการ</h2></div><button disabled={saving}>{saving?'กำลังบันทึก...':'บันทึก Project'}</button></div><div className="formGrid"><label>ชื่อโครงการ<input required value={project.name} onChange={e=>update('name',e.target.value)}/></label><label>Pipeline<select value={project.status} onChange={e=>update('status',e.target.value)}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>มูลค่าโครงการ (บาท)<input type="number" min="0" value={project.project_value} onChange={e=>update('project_value',Number(e.target.value))}/></label><label>ผู้รับผิดชอบ<input value={project.owner||''} onChange={e=>update('owner',e.target.value)}/></label><label className="full">สถานที่ติดตั้ง<input value={project.site_address||''} onChange={e=>update('site_address',e.target.value)}/></label><label className="full">บันทึกโครงการ<textarea value={project.note||''} onChange={e=>update('note',e.target.value)}/></label></div></form>
 <section className="detailCard"><div className="cardHead"><div><p className="eyebrow">QUOTATION WORKFLOW</p><h2>ใบเสนอราคา</h2></div></div><form className="quoteForm" onSubmit={createQuote}><label>มูลค่า (บาท)<input required type="number" min="1" value={quote.amount} onChange={e=>setQuote({...quote,amount:e.target.value})}/></label><label>ใช้ได้ถึง<input type="date" value={quote.validUntil} onChange={e=>setQuote({...quote,validUntil:e.target.value})}/></label><label>หมายเหตุ<input value={quote.note} onChange={e=>setQuote({...quote,note:e.target.value})}/></label><button>สร้างใบเสนอราคา</button></form><div className="quoteList">{quotes.map(q=><article key={q.id}><div><b>{q.quotation_number}</b><span>Version {q.version} · {new Date(q.created_at).toLocaleDateString('th-TH')}</span></div><strong>{money(q.amount)}</strong><select value={q.status} onChange={e=>quoteStatus(q.id,e.target.value)}>{Object.entries(quoteStatuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{q.valid_until&&<small>Valid until {new Date(q.valid_until).toLocaleDateString('th-TH')}</small>}</article>)}{!quotes.length&&<p className="empty">ยังไม่มีใบเสนอราคา</p>}</div></section></div>
 <aside className="detailSide"><section className="detailCard"><p className="eyebrow">CONTACT</p><h3>{project.contact_name}</h3><a href={`tel:${project.phone}`}>{project.phone}</a>{project.email&&<a href={`mailto:${project.email}`}>{project.email}</a>}<span>{project.company||'-'}</span>{project.lead_note&&<p>{project.lead_note}</p>}</section><section className="detailCard"><p className="eyebrow">SOLAR ANALYSIS</p><dl><div><dt>Solar</dt><dd>{Number(project.system_size||0).toFixed(1)} kWp</dd></div><div><dt>Battery</dt><dd>{Number(project.battery_kwh||0).toFixed(1)} kWh</dd></div><div><dt>ประหยัด/ปี</dt><dd>{money(project.saving)}</dd></div><div><dt>Payback</dt><dd>{Number(project.payback||0).toFixed(1)} ปี</dd></div></dl>{project.lat&&project.lng&&<a className="mapLink" target="_blank" rel="noreferrer" href={`https://maps.google.com/?q=${project.lat},${project.lng}`}>เปิดตำแหน่งติดตั้ง ↗</a>}</section></aside></section></main>
}
